services:
  - type: web
    name: train-reservation-system
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: Train@Reservation01
      - key: DB_HOST
        value: db.adozsmkdxblihnaoodiu.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: postgres
      - key: PORT
        generateValue: true
